[package]
name = "rustplus_js_freya"
version = "0.1.0"
edition = "2024"

[dependencies]
freya = { git = "https://github.com/marc2332/freya", branch = "a-new-begining" }
freya-router = { git = "https://github.com/marc2332/freya", branch = "a-new-begining" }
freya-radio = { git = "https://github.com/marc2332/freya", branch = "a-new-begining" }
rustplus_rs = { path = "./rustplus_rs" }
